import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import MainLayout from "@/layouts/MainLayout";
import { Toaster } from "@/components/ui/toaster";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased`}
      >
        <ReduxProvider>
          <MainLayout>{children}</MainLayout>
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
